/// Macros
#macro VIEW_STANDARD_WIDTH 800
#macro VIEW_STANDARD_HEIGHT 450

#macro IDLE 0
#macro RUN 1
#macro SKID 2
#macro DODGE 3
#macro SWING 4
#macro BLOCK 5
#macro PARRY 6
#macro CROUCH 7
#macro JUMP 8
#macro HURT 9
#macro THROWN 10
#macro SWING_JUMP 11
#macro STAND 12
#macro DIE 13
#macro LAND 14
#macro SUICIDE 15
#macro SUICIDE_JUMP 16
#macro SWING_CROUCH 17
#macro SWING_BACK 18

#macro SWORD_NONE -1
#macro SWORD_SWING 0
#macro SWORD_SWING_BACK 1
#macro SWORD_SWING_CROUCH 2
#macro SWORD_BLOCK 3
#macro SWORD_PARRY 4
#macro SWORD_PARRY_BACK 5
#macro SWORD_SUICIDE 6

#macro GRAVITY .5
#macro TERMINAL 50
#macro LANDSPEED 15

#macro PLAYER_HEALTH 10

#macro WALKSPEED 4.5
#macro DODGESPEED 14
#macro DODGE_ENDSPEED 10// 9
#macro JUMPSPEED 10
#macro ATTACKSPEED 10
#macro ATTACK_BACKSPEED 7
#macro ATTACK_DODGESPEED 12

#macro LAST_PRESSED_TIME 15

#macro ATTACK_HIT_INDEX 1
#macro ATTACK_CHAIN_INDEX 3
#macro ATTACK_IMAGE_SPEED .75

#macro FOREGROUND_DEPTH3 -3000
#macro FOREGROUND_DEPTH2 -2000
#macro FOREGROUND_DEPTH1 -1000
#macro PLAYER_DEPTH 0
#macro ENEMY_DEPTH 10
#macro ROCK_DEPTH 100
#macro BACKGROUND_DEPTH1 1000
#macro BACKGROUND_DEPTH2 2000
#macro BACKGROUND_DEPTH3 3000
